#!/usr/bin/env ruby
ENV['RAILS_ENV'] = ARGV.first || 'development'
puts "Loading #{ENV['RAILS_ENV']} environment"
require File.expand_path(File.dirname(__FILE__) + "/../config/environment") unless defined?(RAILS_ROOT)

require 'lib/swf'
Swf.get
